
java_binary(
  name = 'gson',
  srcs = glob(
  [
    "src/main/java/com/chb/*.java",

  ]),
  main_class = "com.chb.Main",
  deps = [
    "@maven//:com_google_inject_guice",
    "@maven//:com_google_code_gson_gson",
  ],
)

